
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(800, 800)
        MainWindow.setGeometry(1520,591,400,400)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0);")
        MainWindow.setWindowFlags(QtCore.Qt.Window | Qt.WindowStaysOnTopHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0,0,400, 320))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("talking.gif"))
        # self.label.setPixmap(QtGui.QPixmap("blueorb.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("jarvis/tumblr_o7vs1zNO341runoqyo6_540.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("jarvis/05bd96100762b05b616fb2a6e5c223b4_w200.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("jarvis/4be66f1aea5e87a674461cff90ff51bc.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("jarvis/Screen_C_Loop_v001.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("jarvis/rotating.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("talking.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("talking.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("talking.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("talking.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("jarvis/f424b7131782573.619c1afdda994.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 330, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPixelSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-image: url(jarvis/btn1.jpg);\n"
"    color:white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 330, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPixelSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-image: url(jarvis/btn2.jpg);\n"
"    color:white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("jarvis/extra1.gif"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("jarvis/Screen_I_Loop_prores_v001.gif"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("jarvis/he-he.gif"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("jarvis/extra4.gif"))
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0,0,10,101))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("jarvis/Owl_SW_Attack_Mode_Generic_Loop_v001.gif"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(0,0,10,10))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("jarvis/Owl_SW_Flight_Mode_Generic_Loop_v001.gif"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        # self.label_16.setText(_translate("MainWindow", "TextLabel"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
